---
- name: call child playbooks for apache2
  hosts: all
  tasks:
    - name: call childs playbooks
      include_tasks: "{{item}}"
      with_items:
         - install.yml
         - edit_index.yml
         -  restart.yml
         - check_url_response.yml

...
