---
- name: capture OS info
  hosts: all
  tasks:
    - name: Capure os name
      debug:
        msg: "{{item}}"
      with_items:
          - "{{ansible_distribution}}"
          - "{{ansible_distribution_version}}"
          - "{{ansible_distribution_major_version}}"

