---
- name: Configuring apache2
  hosts: all
  tasks:
    - name: Install apache2
      apt: 
        name: apache2
        state: present
        update_cache: yes
    - name: Edit the index.html file
      copy: 
        content: "Vijay"
        dest: /var/www/html/index.html
    - name: Restart apache2
      service:
        name: apache2
        state: restarted 
    - name: check apache2 response on server1
      uri: 
        url: http://172.31.35.30
        status_code: 200
    - name: Check apache2 response on server2
      uri:
        url: http://172.31.40.248 
        status_code: 200
...

